# Generated by Django 6.0.6 on 2026-06-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_address_student_age_student_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
